services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    environment:
      - REACT_APP_API_BACKENDS=http://localhost:8001,http://localhost:8002,http://localhost:8003
    depends_on:
      - backend-1
      - backend-2
      - backend-3
    restart: unless-stopped

  backend-1:
    build: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - DYNAMO_ENDPOINT_SECONDARY=http://dynamodb-local-2:8000
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=eu-central-1
    depends_on:
      - dynamodb-local
      - dynamodb-local-2
    restart: unless-stopped

  backend-2:
    build: ./backend
    ports:
      - "8002:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - DYNAMO_ENDPOINT_SECONDARY=http://dynamodb-local-2:8000
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=eu-central-1
    depends_on:
      - dynamodb-local
      - dynamodb-local-2
    restart: unless-stopped

  backend-3:
    build: ./backend
    ports:
      - "8003:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - DYNAMO_ENDPOINT_SECONDARY=http://dynamodb-local-2:8000
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=eu-central-1
    depends_on:
      - dynamodb-local
      - dynamodb-local-2
    restart: unless-stopped

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory
    restart: unless-stopped

  dynamodb-local-2:
    image: amazon/dynamodb-local:latest
    ports:
      - "8004:8000"
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory
    restart: unless-stopped